Run flynt to convert %-formatting to f-strings
pymc-devs/Theano-PyMC pull request #144
Opened 2020-11-04 02:32 UTC by eigenfoo

[WIP, will request review when ready]

A follow-up to #139 - I simply used the [`flynt` CLI tool](https://github.com/ikamensh/flynt) package to automatically convert %-formatted strings to f-strings.

It's important to note that %-formatting are different from f-strings [in meaningful ways](https://github.com/ikamensh/flynt#dangers-of-conversion), so it's important to check the tests.

---

For posterity, here's the output of `flynt`:

```
Running flynt v.0.56

Flynt run has finished. Stats:

Execution time:                            19.170s
Files modified:                            125
Character count reduction:                 2509 (0.03%)

Per expression type:
Old style (`%`) expressions attempted:     846/1483 (57.0%)
`.format(...)` calls attempted:            286/291 (98.3%)
No concatenations attempted.
F-string expressions created:              799
Out of all attempted transforms, 321 resulted in errors.
To find out specific error messages, use --verbose flag.

_-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_._-_.
Please run your tests before committing. Did flynt get a perfect conversion? give it a star at:
~ https://github.com/ikamensh/flynt ~
Thank you for using flynt. Upgrade more projects and recommend it to your colleagues!
```

2020-11-05 01:47 UTC, brandonwillard requested changes
Changes needed:
- [x] I believe that `theano/_version.py` is generated automatically by `versioneer`; if so, we're better off regenerating that file and/or leaving it untouched.
- [x] There are _a lot_ of f-strings containing superfluous uses of `str`, `dict`, and `locals`.  

It would seem as though `flynt` isn't aware of these redundancies.  If you're interested in writing your own refactoring code that _is_ aware of such things, check out [LibCST](https://github.com/Instagram/LibCST)!

2020-11-06 14:21 UTC, eigenfoo commented
@brandonwillard not to dismiss your suggestion, but I just didn't feel like adding to my cognitive load by learning a new tool - I just `rg`ed the diff to find offending instances of `locals()`, `dict`s and `str`s and manually fixed them with some help from Vim macros.

2020-11-06 15:18 UTC, twiecki commented
@eigenfoo seems like tests still fail.

2020-11-06 15:21 UTC, eigenfoo commented
The only test that's failing is the patch coverage, which seems to be failing for all PRs that don't test 100% of their changes. Since this PR doesn't change any actual code behavior, I think that's okay.

2020-11-06 15:25 UTC, twiecki commented
Gotcha, cool.

On Fri, Nov 6, 2020, 16:22 George Ho <notifications@github.com> wrote:

> The only test that's failing is the patch coverage, which seems to be
> failing for all PRs that don't test 100% of their changes. Since this PR
> doesn't change any actual code behavior, I think that's okay.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/pymc-devs/Theano-PyMC/pull/144#issuecomment-723137467>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAFETGHUTRVWLGBZMNXJPOLSOQIB5ANCNFSM4TJPPYAQ>
> .
>

2020-11-08 21:21 UTC, brandonwillard commented
> ...I just didn't feel like adding to my cognitive load by learning a new tool...

Sorry, I wasn't actually suggesting that you use LibCST for the work in this PR.  I was pointing you in the direction of a library that's quite useful for creating your own fully-automated Python refactorings.  It's more of a long-term suggestion, since I strongly believe that Python needs more/better refactoring tools and libraries and I think that's more likely to happen if/when libraries like LibCST are given more attention.

2020-11-08 21:55 UTC, brandonwillard requested changes
Almost there!

It looks like Flynt is restrictively shy about
-  concatenated strings (e.g. `"blah %s " "blah" % "blah"`) and
- interpolations that specify integer presentations (e.g. `"%d"`).

The former can be handled by surrounding the concatenated strings with parentheses and the latter by casting to `int` in the f-string expression.

Otherwise, if I recall, there are some places where the old `%` interpolation is used to create string templates (e.g. `st = "blah %d"; st % 5`).  I don't know if f-strings can be used in that way, so we might need to convert those to `str.format` or `string.Template` forms.  We can create separate issue for that, though.

2020-11-08 21:55 UTC, brandonwillard commented on theano/compile/profiling.py
>                  size = "%10s" % "Unknown"
I wonder why it didn't pick up this one.

2020-11-08 21:55 UTC, brandonwillard commented on theano/gof/cc.py
>                  str(node.op) + " didn't return a string for c_code"
This looks like a good place for an f-string.

2020-11-08 21:55 UTC, brandonwillard commented on theano/gof/compiledir.py
>      print_title("List of %d compiled individual ops" % len(table), underline="+")
This could also be an f-string.

2020-11-08 21:55 UTC, brandonwillard commented on theano/gpuarray/sort.py
>          dims = "".join("dims[%d], " % i for i in reordered_axes[1:])
This could be an f-string, too.

2020-11-08 21:55 UTC, brandonwillard commented on theano/gpuarray/sort.py
>              params_di += "".join("distrides[%d], " % i for i in reordered_axes)
Same here.

2020-11-08 21:55 UTC, brandonwillard commented on theano/gpuarray/type.py
>                  bcast = "%iD" % len(b)
This could also be an f-string.

2020-11-08 21:55 UTC, brandonwillard commented on theano/gradient.py
>                      + " a list of lists, but element %d" % ii
Another f-string candidate.

2020-11-08 21:55 UTC, brandonwillard commented on theano/misc/check_blas.py
>          print("(%d, %d) and (%d, %d)." % (M, N, N, K))
This could also be an f-string.

2020-11-08 21:55 UTC, brandonwillard commented on theano/misc/hooks/check_whitespace.py
>          return "Ambiguous tab at line %d; line is '%s'." % (
Another f-string candidate.

2020-11-08 21:55 UTC, brandonwillard commented on theano/printing.py
>                  " not the result of an operation" % self.function
Another f-string candidate.

2020-11-14 20:11 UTC, eigenfoo commented
I've removed most instances of `%d` - I've replaced them with `f"...{int(x)}..."` in all places, unless it was obvious that it would be an integer instead of a float (e.g. `f"...{len(x)}..."`). I left them alone when they were in templated strings, which should probably be dealt with in a separate issue/PR.

2020-11-15 05:23 UTC, eigenfoo commented
Closed in favor of https://github.com/pymc-devs/Theano-PyMC/pull/162 - we now fork and branch, instead of working off of branches in this repo.

2020-11-15 05:23 UTC, closed without merging