Rename scalar Minimum and Maximum Ops
pymc-devs/Theano-PyMC pull request #227
Opened 2020-12-16 12:43 UTC by michaelosthege

I'm not so sure if this is a good idea.

Maybe the other scalar Ops like `Add` should also be renamed?

2020-12-16 21:39 UTC, brandonwillard requested changes
This is a tough one, because the `Op`s are already prefixed by `scalar` via their package name, so there's a bit of redundancy to this change.  

Perhaps that informative package prefix is lost when objects are imported, but that could be retained/regained with something like `from theano.scalar.basic import maximum as scalar_maximum, Maximum as ScalarMaximum`.

2020-12-16 21:49 UTC, michaelosthege commented
Changing the imports is just code style. Renaming the Ops is a different level.
Do you want to rename the Ops, or just change the import style? (From #55 I understood it was about a real rename.)

Personally, I strongly dislike import aliasing, because it can be really confusing. (Yes, I don't even alias `pandas`, `numpy` or `pyplot`.)
In this PR it also made refactoring unnecessarily hard. In one instance `theano.scalar` was aliased as `ts` and in many others as `scal` 😬

My preferred code style would be `from theano import scalar` without aliasing anything.

2020-12-26 08:28 UTC, michaelosthege commented
@brandonwillard (how) do we want to move forward with this?

2020-12-26 09:55 UTC, twiecki commented on theano/tensor/basic.py
> +        if symbolname in "minimum,maximum,minimum_inplace,maximum_inplace":
TIL

2021-01-02 23:25 UTC, brandonwillard commented
OK, I've rebased and refactored some of the utility functions that were duplicated between `theano.tensor` and `theano.scalar` (e.g. the `_scal_elemwise` decorator).

2021-01-03 00:13 UTC, merged