Rename theano.gof objects
pymc-devs/Theano-PyMC pull request #261
Opened 2021-01-03 20:58 UTC by brandonwillard

This PR introduces a few new important refactorings in `theano.gof`.  Most are renamings of basic classes and utility functions that clarify their purpose/use (e.g. `theano.gof.graph.inputs` is renamed to `theano.gof.graph.graph_inputs` so that it's use doesn't clash with ubiquitous local variables also named `inputs`).

More importantly, this PR includes a rename of `Type` to `CType`, which involves some important `CLinker` changes.  Those changes also improve the clarity of `CLinker`'s code by removing a lot of ambiguous logic (e.g. `try` statements) that allow objects to forego an ultimately required C code-generating interface.

2021-01-04 19:47 UTC, michaelosthege requested changes
Looks really good! Just a few details..
This `contextlib.suppress` is a real hidden gem!

2021-01-04 19:47 UTC, michaelosthege commented on theano/compile/ops.py
> +    if any(not isinstance(t, theano.CType) for t in itypes):
This reference goes through `theano.*`

2021-01-04 19:47 UTC, michaelosthege commented on theano/gof/graph.py
> +        inputs: list of Variables
In numpydoc, there should be a space to both sides of the colon: https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring

2021-01-06 22:15 UTC, twiecki commented on doc/JaxOps.rst
> +   @jax_funcify.register(Eye) # The decorater
```suggestion
   @jax_funcify.register(Eye) # The decorator
```

2021-01-09 12:08 UTC, twiecki approved these changes

2021-01-09 12:08 UTC, twiecki commented
Agree, this looks really great. For your consideration:
Rename `basic` to `core` and `fg` to `function` (so that it's `graph.function.FunctionGraph`. Not super excited about them but tossing them out in case you like them better.

2021-01-09 14:25 UTC, michaelosthege approved these changes
This is great!

I also tend to use "core" submodules, but this codebase uses "basic" in so many places that I don't think we should break with that style.

I noticed a few string formatting problems in the `__author__` fields. But for the sake of reviewability, I think this should be addressed later on.

2021-01-09 18:31 UTC, brandonwillard commented
> I also tend to use "core" submodules, but this codebase uses "basic" in so many places that I don't think we should break with that style.

`core` would be better, but, yes, I decided to go with the existing convention.  We can definitely change that though&mdash;although we should do that for all the modules at once.

> I noticed a few string formatting problems in the `__author__` fields. But for the sake of reviewability, I think this should be addressed later on.

We need to completely remove those nonsense dunder fields in the source files.  More specifically, we should move all the `__copyright__`s to the `LICENSE` file&mdash;if they aren't already covered by what's in there.  Otherwise, outside of externally contributed files, authorship is automatically well documented by Git itself, so those `__author__` fields are superfluous.

2021-01-09 18:44 UTC, twiecki commented
Let's merge this then. But need to make sure to also fix PyMC3.

2021-01-09 18:57 UTC, merged