Implement improved numerically-stable softplus
pymc-devs/Theano-PyMC pull request #262
Opened 2021-01-04 17:34 UTC by ricardoV94

This PR alters the Softplus Op to use the numerically stable approximation described by [Machler 2012](https://cran.r-project.org/web/packages/Rmpfr/vignettes/log1mexp-note.pdf).

It is also computationally efficient in that it uses safe and fast altenatives to the good default `log1p(exp(x))`:

1. `exp(x)` in the range `[-inf, -37]` (not used previously)
2. `log1p(exp(x))` in the range `[-37, 18]` (previously used in the range `[-30, 30]` in Python or `[-inf/underflow, 14/16]` in `c_code`)
2. `x + np.exp(-x)` in the range `[18, 33.3]` (not used previously)
3. `x` in the range `[33.3, +inf]` (previously used in the range `[30, +inf]` in Python or `[14/16, +inf]` in `c_code`)

The previous 64-bit `c_code` cutoff at `16.0` for when to use the approximation `log1p(x) = x` was a bit too eager (according to Machler, and my tests below) and the rational for it was not clear either (the op was described as having the goal of numerical stabilization and not speedup). In addition, the Python version was not doing the same thing as the C counterpart.

According to my tests, there was no issue with the (also unexplained) 32-bit cutoff of `14.0`.

When it comes to unittests, the only thing that was checking for precision seems to have been the `TestSoftplus` in `test.sigm.py` via `verify_grad` which is not sensitive enough to detect the reduction in error introduced by this PR. It can, however, detect when very wrong cutoffs or obviously wrong approximations are used in the `c_code` so it is a good sanity check that the current PR is not breaking anything. I added a new line to test that the gradient is correct in the range `[-40, 40]` since before it was only testing in `[0, 1]`.

Let me know if you think more targeted unit tests are in order. If so, it would be great if you could direct me to examples that are doing something similar to what I should do.

If it helps, I used the following snippet to test the 32 and 64bit `c_code` locally (not sure how to force Theano to use the Python version):

```python
import numpy as np
from theano.tensor.nnet.sigm import softplus

dtype_tol = {
    np.float32: 10e-7,
    np.float64: 10e-16,
}
for dtype, tol in dtype_tol.items():
    print(dtype, tol)
    x = np.linspace(-40, 40, 80, dtype=dtype)
    y_np = np.log1p(np.exp(x))
    y_th = softplus(x).eval()
    np.testing.assert_allclose(y_np, y_th, rtol=tol)
```
The previous 64bit implementation would fail starting at `10e-10` whereas the new (or the old one with the correct cutoff) can go down to the predicted 10e-16 error (I used `theano-cache purge` between runs to make sure I was testing different versions of the `c_code`). 

The 32bit wouldn't fail in the previous implementation due to its limited range (and in fact could have been further optimized), but I think it is better to keep the same implementation for simplicity sake. It is a bit more conservative/inefficient than needed, but not less accurate!

***

Here are a few important guidelines and requirements to check before your PR can be merged:
+ [x] There is an informative high-level description of the changes.
+ [x] The description and/or commit message(s) references the relevant GitHub issue(s).
+ [x] [`pre-commit`](https://pre-commit.com/#installation) is installed and [set up](https://pre-commit.com/#3-install-the-git-hook-scripts).
+ [ ] The commit messages follow [these guidelines](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes), and there are **no commits that fix changes introduced by other commits in the same branch/BR**.  If your commit description starts with "Fix...", then you're probably making this mistake.
+ [ ] There are tests covering the changes introduced in the PR.

Closes #260

2021-01-04 19:37 UTC, brandonwillard requested changes
Ideally, we wouldn't need to maintain our own numerical implementations (and their tests), instead we would only dispatch to established numerical libraries like NumPy and SciPy.  This module has already undergone related changes recently and I'm starting to think we should be looking to our "dispatch" libraries for a set of standard implementations (Python ones, at least) and stick with those.

Is there a NumPy/SciPy implementation that satisfies these accuracy concerns?  Also, note that there is a distinct `Op` for an "ultra fast" sigmoid; we could/should do the same for softplus, if we want to introduce alternative formulations for speed.

2021-01-04 19:37 UTC, brandonwillard commented on tests/tensor/nnet/test_sigm.py
> +        utt.verify_grad(softplus, [np.linspace(-40, 40, 20)])
In this repository, we're moving away from performing wasteful, time consuming, shotgun-like numerical tests, so we need to combine these `verify_grad`s into a single one that explicitly tests only important and/or necessary values.

2021-01-04 19:39 UTC, twiecki commented
> Is there a NumPy/SciPy implementation that satisfies these accuracy concerns?

Certainly not if we want a C Op implementation. Not sure we can avoid that.

2021-01-04 21:04 UTC, ricardoV94 commented
> Ideally, we wouldn't need to maintain our own numerical implementations (and their tests), instead we would only dispatch to established numerical libraries like NumPy and SciPy.  This module has already undergone related changes recently and I'm starting to think we should be looking to our "dispatch" libraries for a set of standard implementations (Python ones, at least) and stick with those.

> Is there a NumPy/SciPy implementation that satisfies these accuracy concerns?  

My understanding is that like for the `log1mexp`, there are no specialized implementations in numpy or scipy at the moment.

> Also, note that there is a distinct `Op` for an "ultra fast" sigmoid; we could/should do the same for softplus, if we want to introduce alternative formulations for speed.

I think those ultrafast methods provide a trade-off with worse precision. In this case the changed function should be faster but no less precise than using the default `log1p(exp(x))` for the entire real range. Since there is no trade-off in precision it doesn't seem to be worth it to separate it into different ops in this case (for this particular algorithm).

2021-01-04 22:20 UTC, brandonwillard commented
> My understanding is that like for the `log1mexp`, there are no specialized implementations in numpy or scipy at the moment.

Yeah, I'm not aware of one for that, but we should first consider use functions like `scipy.special.[logsumexp, softmax]` for their respective `Op`s.

> The `log1mexp` does not exist as an op right now, and is instead implemented in the pymc math module. Do you see a reason to prefer one of the approaches above the other?

I think the current PyMC3 `log1mexp` approach is fine.

We would only want to create a new `Op` to wrap a new SciPy/NumPy function, or to use a very specific C/JAX implementation; otherwise, it's generally better to combine existing "primitive" `Op`s, especially since it allows for more optimizations.  Collapsing multiple `Op`s into a single `Op` can remove the chance to apply some optimizations (e.g. a single rewrite for `x / x -> 1` cannot be applied to an `Op` that represents `lambda x, y: 2 * x / y` when the argument `y = x` is given).

Now, there is one exception to this: we can create specialized `Op`s for compositions of simpler `Op`s and apply those _after_ the "optimizations" in a later "specialization" pass over a graph.  In this case, we probably don't want to advertise direct use of such `Op`s.  Also, these `Op`s obviously need to be accompanied by graph rewrites that apply them; otherwise, they wouldn't be used.



> Since there is no trade-off in precision it doesn't seem to be worth it to separate it into different ops in this case (for this particular algorithm).

Those `Op`s are another type of "specialization".  They can be applied explicitly by a user who wants the performance/precision trade-offs they provide; either through direct use of those `Op`s, or through a choice of broad performance-based optimization settings that automatically apply them (similar to the "specialization" stage).

2021-01-04 22:27 UTC, brandonwillard commented
Anyway, I think these changes are probably worth merging, but my primary concern is that we don't unnecessarily add more time to our test suite.  Find a few important points in the domain that confirm your implementation works and provide full coverage; otherwise, we'll have to trust the underlying numerical libraries and the referenced paper for the rest.

2021-01-05 08:45 UTC, ricardoV94 commented
> Anyway, I think these changes are probably worth merging, but my primary concern is that we don't unnecessarily add more time to our test suite. Find a few important points in the domain that confirm your implementation works and provide full coverage; otherwise, we'll have to trust the underlying numerical libraries and the referenced paper for the rest.

I added what I hope is a lightweight enough test for the critical points of the new algorithm. The precision is set high enough that it would trigger with the previous implementation (64-bit), but not with the current one. 

Given the concern about reducing the speed of the tests, why not cut down the previous test based on the gradient from `[np.random.rand(3, 4)]` to `[np.random.rand(2, 3)]`? Not sure if much time would be saved, but if the test with 12 points has been working for years, maybe it is safe to go with 6 points now.

2021-01-05 09:54 UTC, twiecki approved these changes

2021-01-05 22:30 UTC, michaelosthege requested changes
Greta work! (one nitpick)
What are the implications for the `grad` of this `COp`? Does it suffer from the same instabilities?

2021-01-05 22:30 UTC, michaelosthege commented on theano/tensor/nnet/sigm.py
> +    References
Indentation in this block is off

2021-01-06 13:19 UTC, ricardoV94 commented on theano/tensor/nnet/sigm.py
> +    References
Thanks, fixed

2021-01-06 13:23 UTC, ricardoV94 commented
> What are the implications for the `grad` of this `COp`? Does it suffer from the same instabilities?

To be honest I have no idea. Looking at the grad, it seems to rely solely on the `Sigmoid Op`, but other Ops grad may rely on this one.

2021-01-06 14:58 UTC, twiecki approved these changes

2021-01-06 15:54 UTC, merged

2021-01-06 15:55 UTC, twiecki commented
Thanks @ricardoV94!